name: Quality Gates

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run_checks:
    name: Run code checks
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_run_checks.yml@v5.0.0

  run_unit_tests:
    name: Run tests (vitest)
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_run_tests_vitest.yml@v5.0.0
    with:
      COVERAGE_DISABLE: true